In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold,cross_val_score
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [7]:
df=pd.read_csv("drug200.csv")

In [8]:
df.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          200 non-null    int64
 1   Sex          200 non-null    object
 2   BP           200 non-null    object
 3   Cholesterol  200 non-null    object
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB

In [10]:
df.describe()

              Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000

In [11]:
X=df.drop("Drug",axis=1)
y=df["Drug"]

In [12]:
categorical=["Sex","BP","Cholesterol"]
numerical=["Age","Na_to_K"]

In [15]:
preprocessor=ColumnTransformer([
    ("num",StandardScaler(),numerical),
    ("cat",OneHotEncoder(),categorical)
])

In [16]:
pipeline=Pipeline([
    ("preprocessing",preprocessor),
    ("model",LogisticRegression(max_iter=500))
])

In [18]:
kfold=KFold(n_splits=7,shuffle=True,random_state=42)