In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.neighbors import KNeighborsClassifier

In [6]:
df=pd.read_csv("drug200.csv")

In [7]:
df.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          200 non-null    int64
 1   Sex          200 non-null    object
 2   BP           200 non-null    object
 3   Cholesterol  200 non-null    object
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB

In [9]:
df=pd.get_dummies(df,columns=["Sex","BP","Cholesterol"],drop_first=True)

In [10]:
df.tail()

     Age  Na_to_K   Drug  Sex_M  BP_LOW  BP_NORMAL  Cholesterol_NORMAL
195   56   11.567  drugC  False    True      False               False
196   16   12.006  drugC   True    True      False               False
197   52    9.894  drugX   True   False       True               False
198   23   14.020  drugX   True   False       True                True
199   40   11.349  drugX  False    True      False                True

In [12]:
le=LabelEncoder()
df["Drug"]=le.fit_transform(df["Drug"])

In [13]:
X=df.drop("Drug",axis=1)
y=df["Drug"]

In [ ]:
ss=StandardScaler()
X=ss.fit_transform