In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [3]:
df=pd.read_csv("Naive-Bayes-Classification-Data.csv")

In [4]:
df.head()

   glucose  bloodpressure  diabetes
0       40             85         0
1       40             92         0
2       45             63         1
3       45             80         0
4       40             73         1

In [14]:
df.columns

Index(['glucose', 'bloodpressure', 'diabetes'], dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 995 entries, 0 to 994
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   glucose        995 non-null    int64
 1   bloodpressure  995 non-null    int64
 2   diabetes       995 non-null    int64
dtypes: int64(3)
memory usage: 23.4 KB

In [7]:
df.describe()

          glucose  bloodpressure    diabetes
count  995.000000     995.000000  995.000000
mean    44.306533      79.184925    0.500503
std      6.707567       9.340204    0.500251
min     20.000000      50.000000    0.000000
25%     40.000000      72.000000    0.000000
50%     45.000000      80.000000    1.000000
75%     50.000000      87.000000    1.000000
max     70.000000     100.000000    1.000000

In [8]:
df.isnull().sum()

glucose          0
bloodpressure    0
diabetes         0
dtype: int64

In [15]:
X=df[["glucose","bloodpressure"]]
y=df["diabetes"]

In [16]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [18]:
model=GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

In [19]:
y_pred=model.predict(X_test)

In [20]:
print("Accuracy: ",accuracy_score(y_test,y_pred))
print(classification_report())

Accuracy:  0.9296482412060302