In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [3]:
df=pd.read_csv("vitamin_deficiency_disease_dataset_20260123.csv")

In [4]:
df.head()

,age,gender,bmi,smoking_status,alcohol_consumption,exercise_level,diet_type,sun_exposure,income_level,latitude_region,...,has_night_blindness,has_fatigue,has_bleeding_gums,has_bone_pain,has_muscle_weakness,has_numbness_tingling,has_memory_problems,has_pale_skin,disease_diagnosis,has_multiple_deficiencies
0,79,Male,24.8,Former,NaN,Active,Vegetarian,High,High,Mid,...,0,0,0,0,0,0,0,0,Healthy,0
1,77,Female,39.9,Former,Moderate,Light,Omnivore,Low,Low,Low,...,0,0,0,1,0,0,0,0,Rickets_Osteomalacia,0
2,24,Male,26.4,Former,Heavy,Moderate,Omnivore,Low,High,High,...,1,0,0,0,0,0,0,0,Healthy,0
3,69,Male,23.1,Never,Heavy,Moderate,Vegetarian,High,Low,Low,...,0,0,0,0,0,1,1,0,Anemia,0
4,63,Male,29.6,Never,NaN,Moderate,Vegetarian,Moderate,High,Low,...,0,0,0,0,0,0,0,0,Healthy,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 34 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age                        4000 non-null   int64
 1   gender                     4000 non-null   object
 2   bmi                        4000 non-null   float64
 3   smoking_status             4000 non-null   object
 4   alcohol_consumption        2722 non-null   object
 5   exercise_level             4000 non-null   object
 6   diet_type                  4000 non-null   object
 7   sun_exposure               4000 non-null   object
 8   income_level               4000 non-null   object
 9   latitude_region            4000 non-null   object
 10  vitamin_a_percent_rda      4000 non-null   float64
 11  vitamin_c_percent_rda      4000 non-null   float64
 12  vitamin_d_percent_rda      4000 non-null   float64
 13  vitamin_e_percent_rda      4000 non-null   float64
 14  vitamin_b12_percent_rda    4000 non-null   float64
 15  folate_percent_rda         4000 non-null   float64
 16  calcium_percent_rda        4000 non-null   float64
 17  iron_percent_rda           4000 non-null   float64
 18  hemoglobin_g_dl            4000 non-null   float64
 19  serum_vitamin_d_ng_ml      4000 non-null   float64
 20  serum_vitamin_b12_pg_ml    4000 non-null   float64
 21  serum_folate_ng_ml         4000 non-null   float64
 22  symptoms_count             4000 non-null   int64
 23  symptoms_list              2672 non-null   object
 24  has_night_blindness        4000 non-null   int64
 25  has_fatigue                4000 non-null   int64
 26  has_bleeding_gums          4000 non-null   int64
 27  has_bone_pain              4000 non-null   int64
 28  has_muscle_weakness        4000 non-null   int64
 29  has_numbness_tingling      4000 non-null   int64
 30  has_memory_problems        4000 non-null   int64
 31  has_pale_skin              4000 non-null   int64
 32  disease_diagnosis          4000 non-null   object
 33  has_multiple_deficiencies  4000 non-null   int64
dtypes: float64(13), int64(11), object(10)
memory usage: 1.0+ MB

In [6]:
df.describe()

,age,bmi,vitamin_a_percent_rda,vitamin_c_percent_rda,vitamin_d_percent_rda,vitamin_e_percent_rda,vitamin_b12_percent_rda,folate_percent_rda,calcium_percent_rda,iron_percent_rda,...,symptoms_count,has_night_blindness,has_fatigue,has_bleeding_gums,has_bone_pain,has_muscle_weakness,has_numbness_tingling,has_memory_problems,has_pale_skin,has_multiple_deficiencies
count,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,...,4000.00000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000
mean,50.766250,26.105325,90.770850,89.199075,72.216388,89.946125,62.743225,90.382275,82.586300,76.211125,...,1.86725,0.102250,0.269250,0.043500,0.300750,0.265750,0.351250,0.303000,0.161750,0.347250
std,19.306237,4.922746,37.083534,37.505809,42.831000,37.444649,37.396636,37.563684,36.359131,33.226984,...,1.79581,0.303015,0.443626,0.204005,0.458641,0.441787,0.477421,0.459613,0.368267,0.476156
min,18.000000,15.000000,10.000000,10.000000,7.000000,10.000000,10.000000,10.000000,10.000000,10.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,34.000000,22.800000,62.600000,60.975000,40.730000,61.700000,32.700000,61.800000,55.600000,51.400000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,51.000000,26.200000,85.500000,83.500000,62.270000,84.050000,55.600000,84.800000,77.100000,71.250000,...,2.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,67.000000,29.400000,115.300000,113.000000,93.317500,114.100000,84.500000,115.200000,105.300000,95.900000,...,3.00000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000
max,84.000000,45.000000,219.000000,250.000000,275.600000,237.600000,243.600000,226.600000,232.700000,211.400000,...,9.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [7]:
df.isnull().sum()

age                             0
gender                          0
bmi                             0
smoking_status                  0
alcohol_consumption          1278
exercise_level                  0
diet_type                       0
sun_exposure                    0
income_level                    0
latitude_region                 0
vitamin_a_percent_rda           0
vitamin_c_percent_rda           0
vitamin_d_percent_rda           0
vitamin_e_percent_rda           0
vitamin_b12_percent_rda         0
folate_percent_rda              0
calcium_percent_rda             0
iron_percent_rda                0
hemoglobin_g_dl                 0
serum_vitamin_d_ng_ml           0
serum_vitamin_b12_pg_ml         0
serum_folate_ng_ml              0
symptoms_count                  0
symptoms_list                1328
has_night_blindness             0
has_fatigue                     0
has_bleeding_gums               0
has_bone_pain                   0
has_muscle_weakness             0
has_numbness_tingling           0
has_memory_problems             0
has_pale_skin                   0
disease_diagnosis               0
has_multiple_deficiencies       0
dtype: int64

In [8]:
df["alcohol_consumption"]=df["alcohol_consumption"].fillna(df["alcohol_consumption"].mode()[0])

In [9]:
df=df.drop("symptoms_list",axis=1)

In [10]:
df.isnull().sum()

age                          0
gender                       0
bmi                          0
smoking_status               0
alcohol_consumption          0
exercise_level               0
diet_type                    0
sun_exposure                 0
income_level                 0
latitude_region              0
vitamin_a_percent_rda        0
vitamin_c_percent_rda        0
vitamin_d_percent_rda        0
vitamin_e_percent_rda        0
vitamin_b12_percent_rda      0
folate_percent_rda           0
calcium_percent_rda          0
iron_percent_rda             0
hemoglobin_g_dl              0
serum_vitamin_d_ng_ml        0
serum_vitamin_b12_pg_ml      0
serum_folate_ng_ml           0
symptoms_count               0
has_night_blindness          0
has_fatigue                  0
has_bleeding_gums            0
has_bone_pain                0
has_muscle_weakness          0
has_numbness_tingling        0
has_memory_problems          0
has_pale_skin                0
disease_diagnosis            0
has_multiple_deficiencies    0
dtype: int64

In [11]:
cat=["gender","smoking_status","alcohol_consumption","exercise_level","diet_type","sun_exposure","income_level","latitude_region"]
df=pd.get_dummies(df,columns=cat)

In [12]:
df.head()

,age,bmi,vitamin_a_percent_rda,vitamin_c_percent_rda,vitamin_d_percent_rda,vitamin_e_percent_rda,vitamin_b12_percent_rda,folate_percent_rda,calcium_percent_rda,iron_percent_rda,...,diet_type_Vegetarian,sun_exposure_High,sun_exposure_Low,sun_exposure_Moderate,income_level_High,income_level_Low,income_level_Middle,latitude_region_High,latitude_region_Low,latitude_region_Mid
0,79,24.8,119.1,147.3,152.88,97.5,102.5,188.9,108.3,97.4,...,True,True,False,False,True,False,False,False,False,True
1,77,39.9,85.7,57.5,32.76,82.7,62.6,51.0,42.6,102.5,...,False,False,True,False,False,True,False,False,True,False
2,24,26.4,48.3,152.1,94.99,169.3,136.2,116.6,136.3,86.4,...,False,False,True,False,True,False,False,True,False,False
3,69,23.1,75.8,51.0,51.48,85.7,31.8,66.5,76.5,60.8,...,True,True,False,False,False,True,False,False,True,False
4,63,29.6,93.3,111.5,62.90,155.6,72.6,124.9,69.4,71.9,...,True,False,False,True,True,False,False,False,True,False

In [13]:
X = df.drop("disease_diagnosis", axis=1)
y = df["disease_diagnosis"]

In [14]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [17]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [18]:
model = SVC(kernel="rbf")
model.fit(X_train,y_train)

SVC()

In [19]:
y_pred = model.predict(X_test)
print("Accuracy:",accuracy_score(y_test,y_pred))

Accuracy: 0.88125