In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score,mean_squared_error

In [5]:
df=pd.read_csv("car_price_prediction.csv")

In [6]:
df.head()

,Car ID,Brand,Year,Engine Size,Fuel Type,Transmission,Mileage,Condition,Price,Model
0,1.0,Tesla,2016.0,2.3,Petrol,Manual,114832.0,New,26613.92,Model X
1,2.0,BMW,2018.0,4.4,Electric,Manual,143190.0,Used,14679.61,5 Series
2,3.0,Audi,2013.0,4.5,Electric,Manual,181601.0,New,44402.61,A4
3,4.0,Tesla,2011.0,4.1,Diesel,Automatic,68682.0,New,86374.33,Model Y
4,5.0,Ford,2009.0,2.6,Diesel,Manual,223009.0,Like New,73577.10,Mustang

In [7]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car ID        2250 non-null   float64
 1   Brand         2250 non-null   object
 2   Year          2250 non-null   float64
 3   Engine Size   2250 non-null   float64
 4   Fuel Type     2250 non-null   object
 5   Transmission  2250 non-null   object
 6   Mileage       2250 non-null   float64
 7   Condition     2250 non-null   object
 8   Price         2250 non-null   float64
 9   Model         2250 non-null   object
dtypes: float64(5), object(5)
memory usage: 195.4+ KB

            Car ID         Year  Engine Size        Mileage         Price
count  2250.000000  2250.000000  2250.000000    2250.000000   2250.000000
mean   1251.243556  2011.577778     3.485467  150236.178222  52506.874391
std     725.637358     6.980468     1.427690   88150.746556  27232.417079
min       1.000000  2000.000000     1.000000      15.000000   5011.270000
25%     627.250000  2005.000000     2.300000   71178.500000  28985.052500
50%    1249.500000  2012.000000     3.450000  149762.000000  53485.240000
75%    1875.250000  2018.000000     4.700000  226299.000000  75560.340000
max    2500.000000  2023.000000     6.000000  299967.000000  99982.590000

In [8]:
df.columns

Index(['Car ID', 'Brand', 'Year', 'Engine Size', 'Fuel Type', 'Transmission',
       'Mileage', 'Condition', 'Price', 'Model'],
      dtype='object')

In [9]:
df.isnull().sum()

Car ID          250
Brand           250
Year            250
Engine Size     250
Fuel Type       250
Transmission    250
Mileage         250
Condition       250
Price           250
Model           250
dtype: int64

In [11]:
for col in df.select_dtypes(include=np.number):
    df[col] = df[col].fillna(df[col].median())

for col in df.select_dtypes(include='object'):
    df[col] = df[col].fillna(df[col].mode()[0])